{
    "melee weapon enchantments": [
        {
            "name": "Impervious",
            "base_price": "3000",
            "magic_level": "0",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Glamered",
            "base_price": "4000",
            "magic_level": "0",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Transformative",
            "base_price": "10000",
            "magic_level": "0",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Dueling",
            "base_price": "14000",
            "magic_level": "0",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Allying",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Aberration Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Animal Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Construct Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Dragon Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Fey Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Magical Beast Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Monstrous Humanoid Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Ooze Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Plant Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Undead Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Vermin  Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Humanoid Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Outsider Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "bane"
        },
        {
            "name": "Benevolent",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Called",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Conductive",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Corrosive",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "corrosive"
        },
        {
            "name": "Countering",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Courageous",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Cruel",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Cunning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Deadly",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Defending",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Dispelling",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "dispelling"
        },
        {
            "name": "Flaming",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "flaming"
        },
        {
            "name": "Frost",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "frost"
        },
        {
            "name": "Furious",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Ghost touch",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Grayflame",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Grounding",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Guardian",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Heartseeker",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Huntsman",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Jurist",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Keen",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Ki focus",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Limning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Menacing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Merciful",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Mighty cleaving",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "3",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Mimetic",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Neutralizing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Ominous",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Planar",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Quenching",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Seaborne",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Shock",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "shock"
        },
        {
            "name": "Spell storing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Thawing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Throwing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Thundering",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Unaligned",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Valiant",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Vicious",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "3",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Advancing",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Anarchic",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Anchoring",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Axiomatic",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Corrosive burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "7",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "corrosive"
        },
        {
            "name": "Defiant",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Dispelling burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "dispelling"
        },
        {
            "name": "Disruption",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Flaming burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "flaming"
        },
        {
            "name": "Furyborn",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Glorious",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Holy",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Icy burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "frost"
        },
        {
            "name": "Igniting",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Impact",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes"
        },
        {
            "name": "Invigorating",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Ki intensifying",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Lifesurge",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Negating",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Phase locking",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Planestriking",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Shocking burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes",
            "shared": "shock"
        },
        {
            "name": "Stalking",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "1",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Unholy",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "7",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Wounding",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "9",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Nullifying",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "20",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Repositioning",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "20",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Speed",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "40",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Spell stealing",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "20",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Brilliant energy",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "40",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Dancing",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "40",
            "source": "PZO1123",
            "type": "melee",
            "blunt": "yes",
            "piercing": "yes",
            "slashing": "yes",
            "light_weapon": "yes"
        },
        {
            "name": "Vorpal",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "10",
            "source": "PZO1123",
            "type": "melee",
            "slashing": "yes",
            "light_weapon": "yes"
        }
    ],
    "ranged weapon enchantments": [
        {
            "name": "Adaptive",
            "base_price": "1000",
            "magic_level": "0",
            "frequency": "100",
            "Source": "PZO1123",
            "type": "ranged",
            "bow": "yes"
        },
        {
            "name": "Impervious",
            "base_price": "3000",
            "magic_level": "0",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Glamered",
            "base_price": "4000",
            "magic_level": "0",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Aberration Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Animal Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Construct Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Dragon Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Fey Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Magical Beast Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Monstrous Humanoid Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Ooze Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Plant Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Undead Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Vermin  Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Humanoid Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Outsider Bane",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "5",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "bane"
        },
        {
            "name": "Called",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Conductive",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Conserving",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes"
        },
        {
            "name": "Corrosive",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "corrosive"
        },
        {
            "name": "Cruel",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Cunning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Distance",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Flaming",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "flaming"
        },
        {
            "name": "Frost",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "frost"
        },
        {
            "name": "Huntsman",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Jurist",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "4",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Limning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Lucky",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "firearm": "yes",
            "shared": "lucky"
        },
        {
            "name": "Merciful",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "2",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Planar",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Reliable",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "Source": "PZO1123",
            "type": "ranged",
            "firearm": "yes",
            "shared": "reliable"
        },
        {
            "name": "Returning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "thrown": "yes"
        },
        {
            "name": "Seeking",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Shock",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "shock"
        },
        {
            "name": "Thundering",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Anarchic",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "10",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Anchoring",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "firearm": "yes"
        },
        {
            "name": "Axiomatic",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "10",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Corrosive burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "8",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "corrosive"
        },
        {
            "name": "Lesser designating",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "designating"
        },
        {
            "name": "Endless ammunition",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes"
        },
        {
            "name": "Flaming burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "11",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "flaming"
        },
        {
            "name": "Holy",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "10",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Icy burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "11",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "frost"
        },
        {
            "name": "Igniting",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "4",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Phase locking",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Shocking burst",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "10",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "shock"
        },
        {
            "name": "Stalking",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "4",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Unholy",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "10",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Greater lucky",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "25",
            "Source": "PZO1123",
            "type": "ranged",
            "firearm": "yes",
            "shared": "lucky"
        },
        {
            "name": "Greater reliable",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "20",
            "Source": "PZO1123",
            "type": "ranged",
            "firearm": "yes",
            "shared": "reliable"
        },
        {
            "name": "Speed",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "40",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Brilliant energy",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "9",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Greater designating",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "2",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes",
            "shared": "designating"
        },
        {
            "name": "Nimble shot",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "2",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Second chance",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "2",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        },
        {
            "name": "Allying",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "3",
            "Source": "PZO1123",
            "type": "ranged",
            "crossbow": "yes",
            "thrown": "yes",
            "firearm": "yes",
            "other": "yes"
        }
    ],
    "armor enchantments": [
        {
            "name": "Benevolent",
            "base_price": "2000",
            "magic_level": "0",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Poison-resistant",
            "base_price": "2250",
            "magic_level": "0",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Glamered",
            "base_price": "2700",
            "magic_level": "0",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Jousting",
            "base_price": "3750",
            "magic_level": "0",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Shadow",
            "base_price": "3750",
            "magic_level": "0",
            "frequency": "14",
            "source": "PZO1123",
            "type": "armor",
            "shared": "shadow"
        },
        {
            "name": "Slick",
            "base_price": "3750",
            "magic_level": "0",
            "frequency": "14",
            "source": "PZO1123",
            "type": "armor",
            "shared": "slick"
        },
        {
            "name": "Expeditious",
            "base_price": "4000",
            "magic_level": "0",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Creeping",
            "base_price": "5000",
            "magic_level": "0",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Rallying",
            "base_price": "5000",
            "magic_level": "0",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Adhesive",
            "base_price": "7000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Hosteling",
            "base_price": "7500",
            "magic_level": "0",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Radiant",
            "base_price": "7500",
            "magic_level": "0",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Delving",
            "base_price": "10000",
            "magic_level": "0",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Putrid",
            "base_price": "10000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Harmonizing",
            "base_price": "15000",
            "magic_level": "0",
            "frequency": "16",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Improved shadow",
            "base_price": "15000",
            "magic_level": "0",
            "frequency": "16",
            "source": "PZO1123",
            "type": "armor",
            "shared": "shadow"
        },
        {
            "name": "Improved slick",
            "base_price": "15000",
            "magic_level": "0",
            "frequency": "17",
            "source": "PZO1123",
            "type": "armor",
            "shared": "slick"
        },
        {
            "name": "Energy resistance",
            "base_price": "18000",
            "magic_level": "0",
            "frequency": "17",
            "source": "PZO1123",
            "type": "armor",
            "shared": "energy"
        },
        {
            "name": "Martyring",
            "base_price": "18000",
            "magic_level": "0",
            "frequency": "16",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Righteous",
            "base_price": "27000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Unbound",
            "base_price": "27000",
            "magic_level": "0",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Unrighteous",
            "base_price": "27000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Vigilant",
            "base_price": "27000",
            "magic_level": "0",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Determination",
            "base_price": "30000",
            "magic_level": "0",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Greater shadow",
            "base_price": "33750",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "shadow"
        },
        {
            "name": "Greater slick",
            "base_price": "33750",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "slick"
        },
        {
            "name": "Improved energy resistance",
            "base_price": "42000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "energy"
        },
        {
            "name": "Etherealness",
            "base_price": "49000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Undead controlling",
            "base_price": "49000",
            "magic_level": "0",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Greater energy resistance",
            "base_price": "66000",
            "magic_level": "0",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "energy"
        },
        {
            "name": "Billowing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "armor"
        },
        {
            "name": "Cocooning",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "armor"
        },
        {
            "name": "Balanced",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Bitter",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Bolstering",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Champion",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Dastard",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Deathless",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Defiant",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Fortification (light)",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor",
            "shared": "fort"
        },
        {
            "name": "Grinding",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Impervious",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Mirrored",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Spell storing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "7",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Stanching",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Warding",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "6",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Spell resistance (13)",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "12",
            "source": "PZO1123",
            "type": "armor",
            "shared": "SR"
        },
        {
            "name": "Cotraveling",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "armor"
        },
        {
            "name": "Brawling",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "7",
            "source": "Brawling",
            "type": "armor"
        },
        {
            "name": "Fortification (moderate)",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor",
            "shared": "fort"
        },
        {
            "name": "Ghost touch",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Invulnerability",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Shadow blending",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "1",
            "source": "PRG:PA",
            "type": "armor"
        },
        {
            "name": "Spell resistance (15)",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "9",
            "source": "PZO1123",
            "type": "armor",
            "shared": "SR"
        },
        {
            "name": "Titanic",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Wild",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor"
        },
        {
            "name": "Spell resistance (17)",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "17",
            "source": "PZO1123",
            "type": "armor",
            "shared": "SR"
        },
        {
            "name": "Fortification (heavy)",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "fort"
        },
        {
            "name": "Spell resistance (19)",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "8",
            "source": "PZO1123",
            "type": "armor",
            "shared": "SR"
        }
    ],
    "shield enchantments": [
        {
            "name": "Poison-resistant",
            "base_price": "2250",
            "magic_level": "0",
            "frequency": "10",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Rallying",
            "base_price": "5000",
            "magic_level": "0",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Wyrmsbreath",
            "base_price": "5000",
            "magic_level": "0",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Hosteling",
            "base_price": "7500",
            "magic_level": "0",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Radiant",
            "base_price": "7500",
            "magic_level": "0",
            "frequency": "16",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Energy resistance",
            "base_price": "18000",
            "magic_level": "0",
            "frequency": "50",
            "source": "PZO1123",
            "type": "shield",
            "shared": "energy"
        },
        {
            "name": "Determination",
            "base_price": "30000",
            "magic_level": "0",
            "frequency": "11",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Improved energy resistance",
            "base_price": "42000",
            "magic_level": "0",
            "frequency": "16",
            "source": "PZO1123",
            "type": "shield",
            "shared": "energy"
        },
        {
            "name": "Undead controlling",
            "base_price": "49000",
            "magic_level": "0",
            "frequency": "11",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Greater energy resistance",
            "base_price": "66000",
            "magic_level": "0",
            "frequency": "17",
            "source": "PZO1123",
            "type": "shield",
            "shared": "energy"
        },
        {
            "name": "Arrow catching",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Bashing",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Blinding",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Clangorous",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Defiant",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Fortification (light)",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield",
            "shared": "fort"
        },
        {
            "name": "Grinding",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Impervious",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Mirrored",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Ramming",
            "base_price": "+1 bonus",
            "magic_level": "1",
            "frequency": "9",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Animated",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "20",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Arrow deflection",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "17",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Merging",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Spell resistance (13)",
            "base_price": "+2 bonus",
            "magic_level": "2",
            "frequency": "18",
            "source": "PZO1123",
            "type": "shield",
            "shared": "SR"
        },
        {
            "name": "Fortification (moderate)",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "17",
            "source": "PZO1123",
            "type": "shield",
            "shared": "fort"
        },
        {
            "name": "Ghost touch",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "17",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Spell resistance (15)",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "17",
            "source": "PZO1123",
            "type": "shield",
            "shared": "SR"
        },
        {
            "name": "Wild",
            "base_price": "+3 bonus",
            "magic_level": "3",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Spell resistance (17)",
            "base_price": "+4 bonus",
            "magic_level": "4",
            "frequency": "50",
            "source": "PZO1123",
            "type": "shield",
            "shared": "SR"
        },
        {
            "name": "Fortification (heavy)",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield",
            "shared": "fort"
        },
        {
            "name": "Reflecting",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield"
        },
        {
            "name": "Spell resistance (19)",
            "base_price": "+5 bonus",
            "magic_level": "5",
            "frequency": "15",
            "source": "PZO1123",
            "type": "shield",
            "shared": "SR"
        }
    ]
}