{
    "Core": [
        {
            "name": "Adamantine",
            "rarity": "50",
            "source": "Core",
            "pfs legal": "yes",
            "lweapon_price": "3000",
            "oweapon_price": "3000",
            "tweapon_price": "3000",
            "rweapon_price": "3000",
            "larmor_price": "5000",
            "marmor_price": "10000",
            "harmor_price": "15000",
            "ammu_price": "60",
            "is_Mwk": "yes",
            "metal": "yes"
        },
        {
            "name": "Alchemical Silver",
            "rarity": "200",
            "source": "Core",
            "pfs legal": "yes",
            "lweapon_price": "20",
            "oweapon_price": "90",
            "tweapon_price": "180",
            "rweapon_price": "180",
            "ammu_price": "2",
            "metal": "yes"
        },
        {
            "name": "Cold Iron",
            "rarity": "400",
            "source": "Core",
            "pfs legal": "yes",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "ammu_price": "special",
            "metal": "yes"
        },
        {
            "name": "Darkwood",
            "rarity": "50",
            "source": "Core",
            "pfs legal": "yes",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "larmor_price": "special",
            "marmor_price": "special",
            "harmor_price": "special",
            "shield_price": "special",
            "ammu_price": "special",
            "is_Mwk": "yes",
            "wood": "yes"
        },
        {
            "name": "Dragonhide",
            "rarity": "20",
            "source": "Core",
            "pfs legal": "yes",
            "larmor_price": "special",
            "marmor_price": "special",
            "harmor_price": "special",
            "shield_price": "special",
            "ammu_price": "special",
            "is_Mwk": "yes"
        },
        {
            "name": "Mithral",
            "rarity": "100",
            "source": "Core",
            "pfs legal": "yes",
            "larmor_price": "1000",
            "marmor_price": "4000",
            "harmor_price": "9000",
            "shield_price": "500",
            "is_Mwk": "yes",
            "metal": "yes"
        },
        {
            "name": "Paueliel",
            "rarity": "5",
            "source": "Core",
            "pfs legal": "yes",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "larmor_price": "special",
            "marmor_price": "special",
            "harmor_price": "special",
            "shield_price": "special",
            "ammu_price": "special",
            "is_Mwk": "yes",
            "wood": "yes"
        }
    ],
    "Adventurers Armory": [
        {
            "name": "Singing Steel",
            "rarity": "5",
            "source": "Adventurers Armory",
            "lweapon_price": "6000",
            "oweapon_price": "6000",
            "tweapon_price": "6000",
            "rweapon_price": "6000",
            "larmor_price": "750",
            "marmor_price": "9000",
            "harmor_price": "12000",
            "shield_price": "7000",
            "is_Mwk": "yes",
            "metal": "yes"
        },
        {
            "name": "Sunsilver",
            "rarity": "5",
            "source": "Adventurers Armory",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "larmor_price": "special",
            "marmor_price": "special",
            "harmor_price": "special",
            "shield_price": "special",
            "ammu_price": "special",
            "is_Mwk": "yes",
            "metal": "yes"
        }
    ],
    "Ultimate Equipment": [
        {
            "name": "Angelskin",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "larmor_price": "1000",
            "marmor_price": "2000",
            "is_Mwk": "yes",
            "metal": "yes",
            "wood": "yes"
        },
        {
            "name": "Blood Crystal",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "1500",
            "oweapon_price": "1500",
            "tweapon_price": "1500",
            "rweapon_price": "1500",
            "ammu_price": "30",
            "metal": "yes",
            "weapon type": "P or S"
        },
        {
            "name": "Darkleaf Cloth",
            "rarity": "50",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "larmor_price": "750",
            "marmor_price": "1500",
            "is_Mwk": "yes",
            "leather-cloth": "yes"
        },
        {
            "name": "Elysian Bronze",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "1000",
            "oweapon_price": "1000",
            "tweapon_price": "1000",
            "rweapon_price": "1000",
            "larmor_price": "1000",
            "marmor_price": "2000",
            "harmor_price": "3000",
            "ammu_price": "20",
            "metal": "yes"
        },
        {
            "name": "Fire-Forged Steel",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "600",
            "oweapon_price": "600",
            "tweapon_price": "600",
            "rweapon_price": "600",
            "larmor_price": "1000",
            "marmor_price": "2500",
            "harmor_price": "3000",
            "metal": "yes"
        },
        {
            "name": "Frost-Forged Steel",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "600",
            "oweapon_price": "600",
            "tweapon_price": "600",
            "rweapon_price": "600",
            "larmor_price": "1000",
            "marmor_price": "2500",
            "harmor_price": "3000",
            "metal": "yes"
        },
        {
            "name": "Greenwood",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "is_Mwk": "yes",
            "wood": "yes"
        },
        {
            "name": "Griffon Mane",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "larmor_price": "200"
        },
        {
            "name": "Living Steel",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "lweapon_price": "500",
            "oweapon_price": "500",
            "tweapon_price": "500",
            "rweapon_price": "500",
            "larmor_price": "500",
            "marmor_price": "1000",
            "harmor_price": "1500",
            "shield_price": "100",
            "ammu_price": "10",
            "metal": "yes"
        },
        {
            "name": "Viridium",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "200",
            "oweapon_price": "200",
            "tweapon_price": "200",
            "rweapon_price": "200",
            "ammu_price": "20"
        },
        {
            "name": "Strengthened Viridium",
            "rarity": "1",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "1200",
            "oweapon_price": "1200",
            "tweapon_price": "1200",
            "rweapon_price": "1200",
            "ammu_price": "40"
        },
        {
            "name": "Whipwood",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "pfs legal": "yes",
            "lweapon_price": "500",
            "oweapon_price": "500",
            "tweapon_price": "500",
            "rweapon_price": "500",
            "wood": "yes"
        },
        {
            "name": "Wyroot (1)",
            "rarity": "10",
            "source": "Ultimate Equipment",
            "lweapon_price": "1000",
            "oweapon_price": "1000",
            "tweapon_price": "1000",
            "rweapon_price": "1000",
            "wood": "yes"
        },
        {
            "name": "Strong Wyroot (2)",
            "rarity": "5",
            "source": "Ultimate Equipment",
            "lweapon_price": "2000",
            "oweapon_price": "2000",
            "tweapon_price": "2000",
            "rweapon_price": "2000",
            "wood": "yes"
        },
        {
            "name": "Powerful Wyroot (3)",
            "rarity": "1",
            "source": "Ultimate Equipment",
            "lweapon_price": "4000",
            "oweapon_price": "4000",
            "tweapon_price": "4000",
            "rweapon_price": "4000",
            "wood": "yes"
        }
    ],
    "Player Companion": [
        {
            "name": "Blackwood",
            "rarity": "10",
            "source": "Player Companion",
            "pfs legal": "yes",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "larmor_price": "special",
            "marmor_price": "special",
            "harmor_price": "special",
            "shield_price": "special",
            "ammu_price": "special",
            "is_Mwk": "yes",
            "wood": "yes"
        },
        {
            "name": "Caphorite",
            "rarity": "10",
            "source": "Player Companion",
            "ammu_price": "10",
            "metal": "yes"
        },
        {
            "name": "Heatstone Plating",
            "rarity": "10",
            "source": "Player Companion",
            "pfs legal": "yes",
            "larmor_price": "800",
            "marmor_price": "1000"
        },
        {
            "name": "Lazurite",
            "rarity": "1",
            "source": "Player Companion",
            "larmor_price": "1500",
            "marmor_price": "2500",
            "harmor_price": "3500"
        },
        {
            "name": "Liquid Glass",
            "rarity": "1",
            "source": "Player Companion",
            "lweapon_price": "800",
            "oweapon_price": "800",
            "tweapon_price": "800",
            "rweapon_price": "800",
            "weapon type": "P or S"
        },
        {
            "name": "Nexavaran Steel",
            "rarity": "1",
            "source": "Player Companion",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "ammu_price": "special"
        },
        {
            "name": "Silversheen",
            "rarity": "10",
            "source": "Player Companion",
            "pfs legal": "yes",
            "lweapon_price": "750",
            "oweapon_price": "750",
            "tweapon_price": "750",
            "rweapon_price": "750",
            "is_Mwk": "yes",
            "metal": "yes",
            "weapon type": "P or S"
        },
        {
            "name": "Sunsilk",
            "rarity": "10",
            "source": "Player Companion",
            "pfs legal": "yes",
            "larmor_price": "6000",
            "marmor_price": "6000",
            "harmor_price": "6000"
        }
    ],
    "Adventure Path": [
        {
            "name": "Abysium",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "0",
            "oweapon_price": "0",
            "tweapon_price": "0",
            "rweapon_price": "0",
            "larmor_price": "0",
            "marmor_price": "0",
            "harmor_price": "0",
            "ammu_price": "0",
            "metal": "yes",
            "wood": "yes"
        },
        {
            "name": "Crypstone",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "500",
            "oweapon_price": "500",
            "tweapon_price": "500",
            "rweapon_price": "500",
            "ammu_price": "10",
            "is_Mwk": "yes",
            "stone": "yes",
            "weapon type": "B"
        },
        {
            "name": "Horacalcium",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "6000",
            "oweapon_price": "6000",
            "tweapon_price": "6000",
            "rweapon_price": "6000",
            "larmor_price": "10000",
            "marmor_price": "30000",
            "harmor_price": "60000",
            "is_Mwk": "yes"
        },
        {
            "name": "Inubrix",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "5000",
            "oweapon_price": "5000",
            "tweapon_price": "5000",
            "rweapon_price": "5000"
        },
        {
            "name": "Noqual",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "500",
            "oweapon_price": "500",
            "tweapon_price": "500",
            "rweapon_price": "500",
            "larmor_price": "4000",
            "marmor_price": "8000",
            "harmor_price": "12000",
            "shield_price": "2000"
        },
        {
            "name": "Cold Siccatite",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "1000",
            "oweapon_price": "1000",
            "tweapon_price": "1000",
            "rweapon_price": "1000",
            "larmor_price": "6000",
            "marmor_price": "6000",
            "harmor_price": "6000",
            "shield_price": "6000"
        },
        {
            "name": "Hot Siccatite",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "1000",
            "oweapon_price": "1000",
            "tweapon_price": "1000",
            "rweapon_price": "1000",
            "larmor_price": "6000",
            "marmor_price": "6000",
            "harmor_price": "6000",
            "shield_price": "6000"
        },
        {
            "name": "Spiresteel",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "2000",
            "oweapon_price": "2000",
            "tweapon_price": "2000",
            "rweapon_price": "2000",
            "larmor_price": "1000",
            "marmor_price": "2000",
            "harmor_price": "3000",
            "shield_price": "2000",
            "is_Mwk": "yes",
            "metal": "yes"
        },
        {
            "name": "Throneglass",
            "rarity": "1",
            "source": "Adventure Path",
            "lweapon_price": "13000",
            "oweapon_price": "13000",
            "tweapon_price": "13000",
            "rweapon_price": "13000"
        },
        {
            "name": "Voidglass",
            "rarity": "5",
            "source": "Adventure Path",
            "lweapon_price": "1000",
            "oweapon_price": "1000",
            "tweapon_price": "1000",
            "rweapon_price": "1000",
            "larmor_price": "1000",
            "marmor_price": "2000",
            "harmor_price": "4500",
            "shield_price": "3000"
        }
    ],
    "Distant Realms Campaign Setting": [
        {
            "name": "Aszite",
            "rarity": "1",
            "source": "Distant Realms Campaign Setting",
            "larmor_price": "750",
            "marmor_price": "750",
            "harmor_price": "1000",
            "is_Mwk": "yes",
            "metal": "yes"
        },
        {
            "name": "Druchite",
            "rarity": "1",
            "source": "Distant Realms Campaign Setting",
            "lweapon_price": "1200",
            "oweapon_price": "1200",
            "tweapon_price": "1200",
            "rweapon_price": "1200",
            "larmor_price": "1000",
            "marmor_price": "1500",
            "harmor_price": "2000",
            "ammu_price": "12"
        }
    ],
    "Comic Book": [
        {
            "name": "Pyre Steel",
            "rarity": "1",
            "source": "Comic Book",
            "lweapon_price": "special",
            "oweapon_price": "special",
            "tweapon_price": "special",
            "rweapon_price": "special",
            "ammu_price": "special",
            "metal": "yes"
        }
    ]
}